services:
  tiangong:
    image: tiangong_infra_ws:kinetic
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiangong_kinetic
    hostname: tiangong_kinetic
    working_dir: /tiangong_infra_ws
    volumes:
      - ./ws:/tiangong_infra_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
    network_mode: host
    gpus: "all"

