services:
  tiangong:
    image: tiangong_infra_ws:noetic
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiangong_noetic
    hostname: tiangong_noetic
    working_dir: /tiangong_infra_ws
    volumes:
      - ./ws:/tiangong_infra_ws          # host workspace → container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # GUI (RViz)
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all   # ensure GLX works
    network_mode: host
    gpus: "all"

