controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pitch_l_joint
      - shoulder_roll_l_joint
      - shoulder_yaw_l_joint
      - elbow_pitch_l_joint
      - elbow_yaw_l_joint
      - wrist_pitch_l_joint
      - wrist_roll_l_joint
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pitch_r_joint
      - shoulder_roll_r_joint
      - shoulder_yaw_r_joint
      - elbow_pitch_r_joint
      - elbow_yaw_r_joint
      - wrist_pitch_r_joint
      - wrist_roll_r_joint
initial:  # Define initial robot poses per group
#  - group: left_arm
#    pose: home

  []